#!/usr/bin/env bash
# vi: ft=bash

set -e
filename=$1
name=$(echo $filename | cut -f 1 -d '.')".core"
echo $name
dotnet run -p flatc/flatc.fsproj $1 > $name
# ./ce.escript fmt $name > $name
cat $name
erlc $name

